pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "."

// Keybindings for the shell's actions. All UNBOUND by default — the user
// assigns combos in Settings → Keybindings. Because Hyprland owns keybinds
// (and this shell targets the Lua config), we generate hypr/binds.generated.lua
// from the saved combos and `hyprctl reload` to apply live. quickshell.lua
// sources that file; an empty/absent file means no shell binds.
QtObject {
    id: root

    // The bindable shell actions. `cmd` is run via hl.dsp.exec_cmd(...).
    readonly property var actions: [
        { key: "launcher",   label: "App launcher",      cmd: "qs ipc call launcher toggle" },
        { key: "settings",   label: "Settings",          cmd: "qs ipc call settings toggle" },
        { key: "lock",       label: "Lock screen",       cmd: "qs ipc call lock lock" },
        { key: "tools",      label: "Tools toolbar",     cmd: Paths.script("tools-toggle.sh") },
        { key: "scratchpad", label: "Scratchpad toggle", cmd: Paths.script("special-toggle.sh") }
    ]

    readonly property string _file: Paths.state("binds.generated.lua")

    function combo(k) { return SettingsService.get("binds." + k, "") }
    function setCombo(k, v) {
        SettingsService.set("binds." + k, (v || "").trim())
        apply()
    }

    function _luaContent() {
        let out = [
            "-- AUTO-GENERATED by Quickshell Settings → Keybindings. Do not edit.",
            "-- Sourced by hypr/quickshell.lua. Unbound actions are omitted.",
            ""
        ]
        for (const a of actions) {
            const c = String(combo(a.key)).trim()
            if (c === "") continue
            out.push('hl.bind("' + c + '", hl.dsp.exec_cmd("' + a.cmd + '"))')
        }
        out.push("")
        return out.join("\n")
    }

    // Re-apply Hyprland config after the file is written, so binds take effect
    // without re-running autostart.
    property Process _reload: Process { command: ["hyprctl", "reload"] }

    property Process _writer: Process {
        onExited: { root._reload.running = false; root._reload.running = true }
    }

    function apply() {
        _writer.command = ["sh", "-c", 'printf "%s" "$2" > "$1"', "_", root._file, root._luaContent()]
        _writer.running = false
        _writer.running = true
    }
}
